Repository Pisin2020/Hacktoberfest-2025, pull requests merged in 2025-10, with the labels that each got.

#1 linear search
  Java/linear search.txt
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest2025

#3 Bank Management Code
  Java/Codes/BankAccount.java
  Java/Codes/BankAccountManager.java
Labels: enhancement, hacktoberfest-accepted, hacktoberfest2025

#4 Games
  Java/Codes/Boyer-Moore.java
  Java/Codes/NumberGuessingGame.java
  Java/Codes/braiscasares.java
Labels: hacktoberfest-accepted, hacktoberfest2025, hacktoberfest, code

#5 technical code and technical documentation
  Java/Codes/Palindromo.java
  Java/Codes/SquareRoot.java
  Java/Notes/Handwritten notes on Linear search.pdf
Labels: documentation, hacktoberfest-accepted, hacktoberfest2025, hacktoberfest, code

#6 todo app
  Java/Codes/Suma.java
  Java/Codes/TodoApp.java
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest2025, hacktoberfest

#8 Create GraphShortestPath.java
  Java/Codes/GraphShortestPath.java
Labels: hacktoberfest-accepted, hacktoberfest2025

#16 Update README.md as open source project in hactoberfest
  README.md
Labels: documentation, good first issue, hacktoberfest-accepted, hacktoberfest
